// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function str(prim) {
  return prim;
}

function Footer(Props) {
  return React.createElement("footer", {
              className: "footer",
              style: {
                borderTop: "1px solid #333"
              }
            }, React.createElement("div", {
                  className: "content has-text-centered"
                }, React.createElement("p", undefined, React.createElement("strong", undefined, React.createElement("i", {
                              className: "far fa-copyright"
                            }), "TomAlcala"), " Blog and Sandbox by ", React.createElement("a", {
                          href: "https://github.com/ThomasMarcel",
                          target: "_blank"
                        }, "Thomas Alcala Schneider"), ".")));
}

var make = Footer;

var $$default = Footer;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
