// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Gatsby$ReactTemplate = require("../bindings/Gatsby.bs.js");

function str(prim) {
  return prim;
}

var github = "../img/github-icon.svg";

var component = ReasonReact.statelessComponent("Navbar");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("nav", {
                          "aria-label": "main-navigation",
                          className: "navbar is-transparent",
                          role: "navigation"
                        }, React.createElement("div", {
                              className: "container"
                            }, React.createElement("div", {
                                  className: "navbar-brand"
                                }, ReasonReact.element(undefined, undefined, Gatsby$ReactTemplate.Link[/* make */0]("/", "navbar-item", "Logo", /* array */[
                                          React.createElement("i", {
                                                className: "fab fa-empire fa-2x"
                                              }),
                                          "TomAlcala"
                                        ])), React.createElement("div", {
                                      className: "navbar-burger burger",
                                      data: "navMenu"
                                    }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                                  className: "navbar-menu",
                                  id: "navMenu"
                                }, React.createElement("div", {
                                      className: "navbar-start has-text-centered"
                                    }, React.createElement("a", {
                                          className: "navbar-item",
                                          href: "/about"
                                        }, "About"), React.createElement("a", {
                                          className: "navbar-item",
                                          href: "/contact"
                                        }, "Contact"), React.createElement("a", {
                                          className: "navbar-item",
                                          href: "/img/thomas_alcala-cv-201901-en-m.pdf",
                                          target: "_blank"
                                        }, "Resume")), React.createElement("div", {
                                      className: "navbar-end has-text-centered"
                                    }, React.createElement("a", {
                                          className: "navbar-item",
                                          href: "https://github.com/ThomasMarcel/tomalcala-cms",
                                          rel: "noopener noreferrer",
                                          target: "_blank"
                                        }, React.createElement("span", undefined, "Curious About the Source Code?"), React.createElement("span", {
                                              className: "icon"
                                            }, React.createElement("img", {
                                                  alt: "Github",
                                                  src: github
                                                })))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (_jsProps) {
        return make(/* array */[]);
      }));

exports.str = str;
exports.github = github;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
