// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Gatsby$ReactTemplate = require("../bindings/Gatsby.bs.js");

function str(prim) {
  return prim;
}

function Simple(Props, _children) {
  var title = Props.title;
  var body = Props.body;
  Props.direction;
  var icon = Props.icon;
  var background = Props.background;
  var action = Props.action;
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "bg-image " + background,
                  style: {
                    border: "0"
                  }
                }, React.createElement("div", {
                      className: "layer opacity-dark"
                    })), React.createElement("div", {
                  className: "content",
                  style: {
                    borderBottom: "0",
                    padding: "2em 4em",
                    position: "relative"
                  }
                }, React.createElement("div", {
                      className: "columns"
                    }, React.createElement("div", {
                          className: "column"
                        }, React.createElement("h1", undefined, title), React.createElement("p", undefined, body), ReasonReact.element(undefined, undefined, Gatsby$ReactTemplate.Link.make(Caml_option.some(action), "btn parallelogram action", undefined, /* array */[React.createElement("div", {
                                        className: "skew-fix"
                                      }, "Read More", React.createElement("i", {
                                            className: "fas fa-caret-right",
                                            style: {
                                              marginLeft: "10px"
                                            }
                                          }))]))), React.createElement("div", {
                          className: "column"
                        }, React.createElement("h1", {
                              className: "is-centered"
                            }, React.createElement("i", {
                                  className: "fa-5x " + icon
                                }))))));
}

var make = Simple;

var $$default = Simple;

exports.str = str;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
