// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Social");

function Social(Props, _children) {
  var linkedin = Props.linkedin;
  var github = Props.github;
  var twitter = Props.twitter;
  var slack = Props.slack;
  var skype = Props.skype;
  return React.createElement("div", {
              style: {
                backgroundColor: "#002266"
              }
            }, React.createElement("div", {
                  className: "content",
                  style: {
                    borderBottom: "1px solid #333",
                    padding: "2em 4em",
                    position: "relative"
                  }
                }, React.createElement("div", {
                      className: "columns"
                    }, React.createElement("div", {
                          className: "column has-text-centered"
                        }, React.createElement("a", {
                              className: "social",
                              href: linkedin,
                              target: "_blank"
                            }, React.createElement("i", {
                                  className: "fa-3x fab fa-linkedin"
                                }))), React.createElement("div", {
                          className: "column has-text-centered"
                        }, React.createElement("a", {
                              className: "social",
                              href: github,
                              target: "_blank"
                            }, React.createElement("i", {
                                  className: "fa-3x fab fa-github-square"
                                }))), React.createElement("div", {
                          className: "column has-text-centered"
                        }, React.createElement("a", {
                              className: "social",
                              href: slack,
                              target: "_blank"
                            }, React.createElement("i", {
                                  className: "fa-3x fab fa-slack"
                                }))), React.createElement("div", {
                          className: "column has-text-centered"
                        }, React.createElement("a", {
                              className: "social",
                              href: skype,
                              target: "_blank"
                            }, React.createElement("i", {
                                  className: "fa-3x fab fa-skype"
                                }))), React.createElement("div", {
                          className: "column has-text-centered"
                        }, React.createElement("a", {
                              className: "social",
                              href: twitter,
                              target: "_blank"
                            }, React.createElement("i", {
                                  className: "fa-3x fab fa-twitter-square"
                                }))))));
}

var make = Social;

var $$default = Social;

exports.str = str;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
