// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Social");

function make(linkedin, github, twitter, slack, skype, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          style: {
                            backgroundColor: "#002266"
                          }
                        }, React.createElement("div", {
                              className: "content",
                              style: {
                                borderBottom: "1px solid #333",
                                padding: "2em 4em",
                                position: "relative"
                              }
                            }, React.createElement("div", {
                                  className: "columns"
                                }, React.createElement("div", {
                                      className: "column has-text-centered"
                                    }, React.createElement("a", {
                                          className: "social",
                                          href: linkedin,
                                          target: "_blank"
                                        }, React.createElement("i", {
                                              className: "fa-3x fab fa-linkedin"
                                            }))), React.createElement("div", {
                                      className: "column has-text-centered"
                                    }, React.createElement("a", {
                                          className: "social",
                                          href: github,
                                          target: "_blank"
                                        }, React.createElement("i", {
                                              className: "fa-3x fab fa-github-square"
                                            }))), React.createElement("div", {
                                      className: "column has-text-centered"
                                    }, React.createElement("a", {
                                          className: "social",
                                          href: slack,
                                          target: "_blank"
                                        }, React.createElement("i", {
                                              className: "fa-3x fab fa-slack"
                                            }))), React.createElement("div", {
                                      className: "column has-text-centered"
                                    }, React.createElement("a", {
                                          className: "social",
                                          href: skype,
                                          target: "_blank"
                                        }, React.createElement("i", {
                                              className: "fa-3x fab fa-skype"
                                            }))), React.createElement("div", {
                                      className: "column has-text-centered"
                                    }, React.createElement("a", {
                                          className: "social",
                                          href: twitter,
                                          target: "_blank"
                                        }, React.createElement("i", {
                                              className: "fa-3x fab fa-twitter-square"
                                            }))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.linkedin, jsProps.github, jsProps.twitter, jsProps.slack, jsProps.skype, /* array */[]);
      }));

exports.str = str;
exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
