// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Random = require("bs-platform/lib/js/random.js");

var colors = /* :: */[
  "purple",
  /* :: */[
    "indigo",
    /* :: */[
      "blue",
      /* :: */[
        "green",
        /* :: */[
          "yellow",
          /* :: */[
            "orange",
            /* :: */[
              "red",
              /* [] */0
            ]
          ]
        ]
      ]
    ]
  ]
];

var max = List.length(colors);

function randColor(param) {
  var rand = Random.$$int(max);
  return List.nth(colors, rand);
}

function randBackground(param) {
  var diff = Random.$$int(4) + 2 | 0;
  var rand1 = Random.$$int(max);
  var match = (rand1 + diff | 0) >= max;
  var rand2 = match ? (rand1 + diff | 0) - max | 0 : rand1 + diff | 0;
  var match$1 = Random.$$int(2);
  var direction = match$1 !== 0 ? "to left" : "to right";
  return "linear-gradient(" + (direction + (", " + (List.nth(colors, rand1) + (", " + (List.nth(colors, rand2) + ")")))));
}

var minDiff = 2;

exports.colors = colors;
exports.max = max;
exports.minDiff = minDiff;
exports.randColor = randColor;
exports.randBackground = randBackground;
/* max Not a pure module */
