// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Utils$ReactTemplate = require("./Utils.bs.js");

for(var i = 1; i <= 100; ++i){
  console.log("Test " + String(i));
  console.log(Utils$ReactTemplate.randBackground(/* () */0));
}

/*  Not a pure module */
